# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todos.proto',
  package='todos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btodos.proto\x12\x05todos\"9\n\nTodoEntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"c\n\x0fTodoListRequest\x12\x1f\n\x04todo\x18\x01 \x01(\x0b\x32\x11.todos.TodoEntity\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x10\n\x08ordering\x18\x04 \x03(\t\"@\n\x11TodoUpdateRequest\x12\x1f\n\x04todo\x18\x01 \x01(\x0b\x32\x11.todos.TodoEntity\x12\n\n\x02id\x18\x02 \x01(\x05\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"a\n\x10TodoListResponse\x12\x1f\n\x04todo\x18\x01 \x03(\x0b\x32\x11.todos.TodoEntity\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\r\n\x05total\x18\x05 \x01(\x05\" \n\x0eResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\xaa\x02\n\x05Todos\x12>\n\tListTodos\x12\x16.todos.TodoListRequest\x1a\x17.todos.TodoListResponse\"\x00\x12\x34\n\nCreateTodo\x12\x11.todos.TodoEntity\x1a\x11.todos.TodoEntity\"\x00\x12\x31\n\x07GetTodo\x12\x11.todos.GetRequest\x1a\x11.todos.TodoEntity\"\x00\x12;\n\nUpdateTodo\x12\x18.todos.TodoUpdateRequest\x1a\x11.todos.TodoEntity\"\x00\x12;\n\nDeleteTodo\x12\x14.todos.DeleteRequest\x1a\x15.todos.ResultResponse\"\x00\x62\x06proto3'
)




_TODOENTITY = _descriptor.Descriptor(
  name='TodoEntity',
  full_name='todos.TodoEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todos.TodoEntity.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='todos.TodoEntity.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completed', full_name='todos.TodoEntity.completed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=79,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='todos.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todos.GetRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=105,
)


_TODOLISTREQUEST = _descriptor.Descriptor(
  name='TodoListRequest',
  full_name='todos.TodoListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='todos.TodoListRequest.todo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='todos.TodoListRequest.offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='todos.TodoListRequest.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ordering', full_name='todos.TodoListRequest.ordering', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=206,
)


_TODOUPDATEREQUEST = _descriptor.Descriptor(
  name='TodoUpdateRequest',
  full_name='todos.TodoUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='todos.TodoUpdateRequest.todo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='todos.TodoUpdateRequest.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=272,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='todos.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todos.DeleteRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=301,
)


_TODOLISTRESPONSE = _descriptor.Descriptor(
  name='TodoListResponse',
  full_name='todos.TodoListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='todos.TodoListResponse.todo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='todos.TodoListResponse.offset', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='todos.TodoListResponse.limit', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='todos.TodoListResponse.total', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=400,
)


_RESULTRESPONSE = _descriptor.Descriptor(
  name='ResultResponse',
  full_name='todos.ResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='todos.ResultResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=434,
)

_TODOLISTREQUEST.fields_by_name['todo'].message_type = _TODOENTITY
_TODOUPDATEREQUEST.fields_by_name['todo'].message_type = _TODOENTITY
_TODOLISTRESPONSE.fields_by_name['todo'].message_type = _TODOENTITY
DESCRIPTOR.message_types_by_name['TodoEntity'] = _TODOENTITY
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['TodoListRequest'] = _TODOLISTREQUEST
DESCRIPTOR.message_types_by_name['TodoUpdateRequest'] = _TODOUPDATEREQUEST
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['TodoListResponse'] = _TODOLISTRESPONSE
DESCRIPTOR.message_types_by_name['ResultResponse'] = _RESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TodoEntity = _reflection.GeneratedProtocolMessageType('TodoEntity', (_message.Message,), {
  'DESCRIPTOR' : _TODOENTITY,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoEntity)
  })
_sym_db.RegisterMessage(TodoEntity)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

TodoListRequest = _reflection.GeneratedProtocolMessageType('TodoListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TODOLISTREQUEST,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoListRequest)
  })
_sym_db.RegisterMessage(TodoListRequest)

TodoUpdateRequest = _reflection.GeneratedProtocolMessageType('TodoUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TODOUPDATEREQUEST,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoUpdateRequest)
  })
_sym_db.RegisterMessage(TodoUpdateRequest)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

TodoListResponse = _reflection.GeneratedProtocolMessageType('TodoListResponse', (_message.Message,), {
  'DESCRIPTOR' : _TODOLISTRESPONSE,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoListResponse)
  })
_sym_db.RegisterMessage(TodoListResponse)

ResultResponse = _reflection.GeneratedProtocolMessageType('ResultResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESULTRESPONSE,
  '__module__' : 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.ResultResponse)
  })
_sym_db.RegisterMessage(ResultResponse)



_TODOS = _descriptor.ServiceDescriptor(
  name='Todos',
  full_name='todos.Todos',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=437,
  serialized_end=735,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListTodos',
    full_name='todos.Todos.ListTodos',
    index=0,
    containing_service=None,
    input_type=_TODOLISTREQUEST,
    output_type=_TODOLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTodo',
    full_name='todos.Todos.CreateTodo',
    index=1,
    containing_service=None,
    input_type=_TODOENTITY,
    output_type=_TODOENTITY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodo',
    full_name='todos.Todos.GetTodo',
    index=2,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_TODOENTITY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTodo',
    full_name='todos.Todos.UpdateTodo',
    index=3,
    containing_service=None,
    input_type=_TODOUPDATEREQUEST,
    output_type=_TODOENTITY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTodo',
    full_name='todos.Todos.DeleteTodo',
    index=4,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_RESULTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOS)

DESCRIPTOR.services_by_name['Todos'] = _TODOS

# @@protoc_insertion_point(module_scope)
