# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import todos_pb2 as todos__pb2


class TodosStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTodos = channel.unary_unary(
                '/todos.Todos/ListTodos',
                request_serializer=todos__pb2.TodoListRequest.SerializeToString,
                response_deserializer=todos__pb2.TodoListResponse.FromString,
                )
        self.CreateTodo = channel.unary_unary(
                '/todos.Todos/CreateTodo',
                request_serializer=todos__pb2.TodoEntity.SerializeToString,
                response_deserializer=todos__pb2.TodoEntity.FromString,
                )
        self.GetTodo = channel.unary_unary(
                '/todos.Todos/GetTodo',
                request_serializer=todos__pb2.GetRequest.SerializeToString,
                response_deserializer=todos__pb2.TodoEntity.FromString,
                )
        self.UpdateTodo = channel.unary_unary(
                '/todos.Todos/UpdateTodo',
                request_serializer=todos__pb2.TodoUpdateRequest.SerializeToString,
                response_deserializer=todos__pb2.TodoEntity.FromString,
                )
        self.DeleteTodo = channel.unary_unary(
                '/todos.Todos/DeleteTodo',
                request_serializer=todos__pb2.DeleteRequest.SerializeToString,
                response_deserializer=todos__pb2.ResultResponse.FromString,
                )


class TodosServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTodos,
                    request_deserializer=todos__pb2.TodoListRequest.FromString,
                    response_serializer=todos__pb2.TodoListResponse.SerializeToString,
            ),
            'CreateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTodo,
                    request_deserializer=todos__pb2.TodoEntity.FromString,
                    response_serializer=todos__pb2.TodoEntity.SerializeToString,
            ),
            'GetTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodo,
                    request_deserializer=todos__pb2.GetRequest.FromString,
                    response_serializer=todos__pb2.TodoEntity.SerializeToString,
            ),
            'UpdateTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTodo,
                    request_deserializer=todos__pb2.TodoUpdateRequest.FromString,
                    response_serializer=todos__pb2.TodoEntity.SerializeToString,
            ),
            'DeleteTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTodo,
                    request_deserializer=todos__pb2.DeleteRequest.FromString,
                    response_serializer=todos__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todos.Todos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Todos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todos.Todos/ListTodos',
            todos__pb2.TodoListRequest.SerializeToString,
            todos__pb2.TodoListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todos.Todos/CreateTodo',
            todos__pb2.TodoEntity.SerializeToString,
            todos__pb2.TodoEntity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todos.Todos/GetTodo',
            todos__pb2.GetRequest.SerializeToString,
            todos__pb2.TodoEntity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todos.Todos/UpdateTodo',
            todos__pb2.TodoUpdateRequest.SerializeToString,
            todos__pb2.TodoEntity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todos.Todos/DeleteTodo',
            todos__pb2.DeleteRequest.SerializeToString,
            todos__pb2.ResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
